#!/bin/bash

function exit_script() {
	if ! [ -z "$CYDIA" ]; then
		read -r fd ver <<EOT
$CYDIA
EOT
        if [ "$ver" -ge 1 ]; then
            echo "finish:$1" >&$fd
        fi
    fi
    exit 0
}

# coolbooter untether support
mkdir /taig
touch /taig/taig

set -o pipefail
/usr/bin/iocaste install
set +o pipefail
exit_script reboot
